# BUILD

FROM gradle:7-jdk11 AS builder

WORKDIR /workdir

RUN git clone https://github.com/wiremock/wiremock .

RUN ./gradlew shadowJar

# RUN

FROM eclipse-temurin:11.0.19_7-jre-alpine

LABEL maintainer="Rodolphe CHAIGNEAU <rodolphe.chaigneau@gmail.com>"

WORKDIR /home/wiremock

RUN apk add --update openssl

# grab su-exec for easy step-down from root
# and bash
RUN apk add --no-cache 'su-exec>=0.2' bash

COPY --from=builder /workdir/build/libs/*.jar /var/wiremock/lib/wiremock-jre8-standalone.jar

COPY docker-entrypoint.sh /

EXPOSE 8080 8443

ENTRYPOINT ["/docker-entrypoint.sh"]
