# BUILD

FROM gradle:7-jdk11 AS builder

WORKDIR /workdir

RUN git clone https://github.com/wiremock/wiremock .

RUN sed -i /Xmx3g/d gradle.properties

RUN ./gradlew shadowJar

# RUN

FROM eclipse-temurin:24.0.2_12-jre

LABEL maintainer="Rodolphe CHAIGNEAU <rodolphe.chaigneau@gmail.com>"

WORKDIR /home/wiremock

COPY --from=builder /workdir/build/libs/*.jar /var/wiremock/lib/wiremock-standalone.jar

COPY docker-entrypoint.sh /

# Init WireMock files structure
RUN mkdir -p /home/wiremock/mappings && \
	mkdir -p /home/wiremock/__files && \
	mkdir -p /var/wiremock/extensions

EXPOSE 8080 8443

HEALTHCHECK --start-period=5s --start-interval=100ms CMD curl -f http://localhost:8080/__admin/health || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
