# BUILD

FROM gradle:7-jdk11 AS builder

WORKDIR /workdir

RUN git clone https://github.com/wiremock/wiremock .

RUN sed -i /Xmx3g/d gradle.properties

RUN ./gradlew shadowJar

# RUN

FROM docker.io/library/eclipse-temurin:20

LABEL maintainer="Rodolphe CHAIGNEAU <rodolphe.chaigneau@gmail.com>"

WORKDIR /home/wiremock

COPY --from=builder /workdir/build/libs/*.jar /var/wiremock/lib/wiremock-standalone.jar

COPY docker-entrypoint.sh /

# Init WireMock files structure
RUN mkdir -p /home/wiremock/mappings && \
	mkdir -p /home/wiremock/__files && \
	mkdir -p /var/wiremock/extensions

EXPOSE 8080 8443

ENTRYPOINT ["/docker-entrypoint.sh"]
